name: "Validate features"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Validate features"
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./src"
